trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      chmod +x gradlew
      ./gradlew clean build
    displayName: 'Build Spring Boot'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build/libs'
      ArtifactName: 'springboot-artifact'
      publishLocation: 'Container'
