trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    pwd
    ls -la
    find . -name gradlew
  displayName: 'Verificar estrutura'

- script: |
    chmod +x gradlew
    ./gradlew clean build
  displayName: 'Build Spring Boot'
